from deque import Deque

d = Deque()

d.add_last(5)
print(d._data)
d.add_first(3)
print(d._data)
d.add_first(7)
print(d._data)
print(d.first())
print(d._data)
print(d.delete_last())
print(d._data)
print(len(d))
print(d._data)
print(d.delete_last())
print(d._data)
print(d.delete_last())
print(d._data)
d.add_first(6)
print(d._data)
print(d.last())
print(d._data)
d.add_first(8)
print(d._data)
print(d.is_empty())
print(d._data)
print(d.last())
print(d._data)